#!/bin/bash
# Extended rofi launcher for ArchBang

nol=7

items="Terminal\0icon\x1futilities-terminal\nFirefox\0icon\x1ffirefox\nFiles\0icon\x1fsystem-file-manager\nApplications\0icon\x1fsystem-run\nTheme\0icon\x1fpreferences-desktop-theme"

if [[ -x ~/Scripts/abinstall ]]; then
  items="$items\nInstall\0icon\x1fsystem-software-install"
  nol=8
fi

items="$items\nKeybinds\0icon\x1finput-keyboard\nExit\0icon\x1fsystem-shutdown"

choice=$(printf "$items" | rofi -dmenu -p "ArchBang" -show-icons \
  -theme-str "listview {lines: $nol;} inputbar { enabled: false; } window { width: 250px; }")

case "$choice" in
Terminal)
  foot
  ;;
Firefox)
  firefox
  ;;
Files)
  thunar
  ;;
Applications)
  rofi -show drun
  ;;
Theme)
  ~/Scripts/themebang
  ;;
Install)
  foot --maximized -e sudo -EH ~/Scripts/abinstall
  ;;
Keybinds)
  grep -E "(Super|Ctrl|Vol|Mute|Alt)" ~/Documents/Keybindings |
    rofi -dmenu -p "Keybinds" -columns 2 -theme-str "listview {lines: 16;}"
  ;;
Exit)
  ~/Scripts/powermenu
  ;;
esac
